version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - my-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: gustavoalvesandrade18@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5433:80
    depends_on:
      - postgres
    networks:
      - my-network
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
    networks:
      - my-network
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: $POSTGRES_PASSWORD
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
      # ROOT_LOGLEVEL: DEBUG
      # KEYCLOAK_LOGLEVEL: DEBUG
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - my-network
  my-service-discovery:
    build:
      context: ./my-service-discovery/
      dockerfile: Dockerfile
    image: my-service-discovery
    ports:
      - 8761:8761
      - 5061:5005
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    depends_on:
      - postgres
    networks:
      - my-network
  my-gateway:
    build:
      context: ./my-gateway/
      dockerfile: Dockerfile
    image: my-gateway
    ports:
      - 8090:8090
      - 5090:5005
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    depends_on:
      - my-service-discovery
    networks:
      - my-network
  my-school:
    build:
      context: ./my-school/
      dockerfile: Dockerfile
    image: my-school
    ports:
      - 8081:8081
      - 5081:5005
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    depends_on:
      - postgres
      - my-gateway
      - my-service-discovery
    networks:
      - my-network
  my-registration:
    build:
      context: ./my-registration/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./my-registration:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - my-gateway
      - my-service-discovery
    networks:
      - my-network
  my-report:
    build:
      context: ./my-report/
      dockerfile: Dockerfile
    image: my-report
    ports:
      - 8083:8083
      - 5083:5005
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    depends_on:
      - postgres
      - my-gateway
      - my-service-discovery
    networks:
      - my-network
    links:
      - mongo_db:app_db
networks:
  my-network:
    driver: bridge
