server:
  port: 8081
  servlet:
    context-path: /my-school

spring:
  application:
    name: my-school
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: jdbc:postgresql://postgres:5432/my-school
    url: postgres
    password: postgres


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://my-service-discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
