server:
  port: 8081
  servlet:
    context-path: /my-school

spring:
  application:
    name: my-school
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/my_school
    username: keycloak
    password: password
  flyway:
    baseline-on-migrate: true
    enabled: true


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://my-service-discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
