server:
  port: 8082

spring:
  application:
    name: my-user

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://my-service-discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true