my-routes:
  urlMySchool: http://my-school:8081
  urlMyUser: http://my-user:8082
  urlMyReport: http://my-report:8083


spring:
  application:
    name: my-gateway


eureka:
  instance:
    hostname: my-gateway
  client:
    service-url:
      defaultZone: http://my-service-discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8090